title: Stinger Analytics and IT
email: Admin@StingerAnalytics.com
description: >- # this means to ignore newlines until "baseurl:"
  Where IT fun and Data Science meet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.StingerAnalytics.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: StingerAnalytic
github_username:  StingerAnalytics

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
